const employeesDataMock = [
    {
        id: 1,
        jobTitleName: "Developer",
        firstName: "Romin",
        lastName: "Irani",
        preferredFullName: "Romin Irani",
        employeeCode: "E1",
        region: "CA",
        dob: "01/10/1993",
        phoneNumber: "408-1234567",
        emailAddress: "romin.k.irani@gmail.com"
    },
    {
        id: 2,
        jobTitleName: "Developer",
        firstName: "Neil",
        lastName: "Irani",
        preferredFullName: "Neil Irani",
        employeeCode: "E2",
        region: "CA",
        dob: "01/10/1992",
        phoneNumber: "408-1111111",
        emailAddress: "neilrirani@gmail.com"
    },
    {
        id: 3,
        jobTitleName: "Program Directory",
        firstName: "Tom",
        lastName: "Hanks",
        preferredFullName: "Tom Hanks",
        employeeCode: "E3",
        region: "CA",
        dob: "05/12/1995",
        phoneNumber: "408-2222222",
        emailAddress: "tomhanks@gmail.com"
    },
    {
        id: 4,
        jobTitleName: "Developer",
        firstName: "Romin",
        lastName: "Irani",
        preferredFullName: "Romin Irani",
        employeeCode: "E4",
        region: "CA",
        dob: "01/10/1993",
        phoneNumber: "408-1234567",
        emailAddress: "romin.k.irani@gmail.com"
    },
    {
        id: 5,
        jobTitleName: "Developer",
        firstName: "Neil",
        lastName: "Irani",
        preferredFullName: "Neil Irani",
        employeeCode: "E5",
        region: "CA",
        dob: "01/10/1992",
        phoneNumber: "408-1111111",
        emailAddress: "neilrirani@gmail.com"
    },
    {
        id: 6,
        jobTitleName: "Program Directory",
        firstName: "Tom",
        lastName: "Hanks",
        preferredFullName: "Tom Hanks",
        employeeCode: "E6",
        region: "CA",
        dob: "05/12/1995",
        phoneNumber: "408-2222222",
        emailAddress: "tomhanks@gmail.com"
    },
    {
        id: 7,
        jobTitleName: "Developer",
        firstName: "Romin",
        lastName: "Irani",
        preferredFullName: "Romin Irani",
        employeeCode: "E7",
        region: "CA",
        dob: "01/10/1993",
        phoneNumber: "408-1234567",
        emailAddress: "romin.k.irani@gmail.com"
    },
    {
        id: 8,
        jobTitleName: "Developer",
        firstName: "Neil",
        lastName: "Irani",
        preferredFullName: "Neil Irani",
        employeeCode: "E8",
        region: "CA",
        dob: "01/10/1992",
        phoneNumber: "408-1111111",
        emailAddress: "neilrirani@gmail.com"
    },
    {
        id: 9,
        jobTitleName: "Program Directory",
        firstName: "Tom",
        lastName: "Hanks",
        preferredFullName: "Tom Hanks",
        employeeCode: "E9",
        region: "CA",
        dob: "05/12/1995",
        phoneNumber: "408-2222222",
        emailAddress: "tomhanks@gmail.com"
    },
    {
        id: 10,
        jobTitleName: "Developer",
        firstName: "Romin",
        lastName: "Irani",
        preferredFullName: "Romin Irani",
        employeeCode: "E10",
        region: "CA",
        dob: "01/10/1993",
        phoneNumber: "408-1234567",
        emailAddress: "romin.k.irani@gmail.com"
    },
    {
        id: 11,
        jobTitleName: "Developer",
        firstName: "Neil",
        lastName: "Irani",
        preferredFullName: "Neil Irani",
        employeeCode: "E11",
        region: "CA",
        dob: "01/10/1992",
        phoneNumber: "408-1111111",
        emailAddress: "neilrirani@gmail.com"
    },
    {
        id: 12,
        jobTitleName: "Program Directory",
        firstName: "Tom",
        lastName: "Hanks",
        preferredFullName: "Tom Hanks",
        employeeCode: "E12",
        region: "CA",
        dob: "05/12/1995",
        phoneNumber: "408-2222222",
        emailAddress: "tomhanks@gmail.com"
    }
]